// <auto-generated />
using System;
using LabRepair.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabRepair.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabRepair.Models.Komputer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KodePc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Kondisi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("Os")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Penyimpanan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Processor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ram")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("KodePc")
                        .IsUnique();

                    b.HasIndex("LabId");

                    b.ToTable("Komputer");
                });

            modelBuilder.Entity("LabRepair.Models.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Lokasi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.ToTable("Lab");
                });

            modelBuilder.Entity("LabRepair.Models.LaporanKerusakan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("KomputerId")
                        .HasColumnType("int");

                    b.Property<int>("PelaporId")
                        .HasColumnType("int");

                    b.Property<string>("Prioritas")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("TanggalLapor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanggalSelesai")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeknisiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KomputerId");

                    b.HasIndex("PelaporId");

                    b.HasIndex("TeknisiId");

                    b.ToTable("LaporanKerusakan");
                });

            modelBuilder.Entity("LabRepair.Models.Pengguna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peran")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Pengguna");
                });

            modelBuilder.Entity("LabRepair.Models.Perbaikan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Biaya")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("LaporanId")
                        .HasColumnType("int");

                    b.Property<string>("Sparepart")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StatusSetelah")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeknisiId")
                        .HasColumnType("int");

                    b.Property<string>("Tindakan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LaporanId");

                    b.HasIndex("TeknisiId");

                    b.ToTable("Perbaikan");
                });

            modelBuilder.Entity("LabRepair.Models.Komputer", b =>
                {
                    b.HasOne("LabRepair.Models.Lab", "Lab")
                        .WithMany("Komputer")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabRepair.Models.LaporanKerusakan", b =>
                {
                    b.HasOne("LabRepair.Models.Komputer", "Komputer")
                        .WithMany("Laporan")
                        .HasForeignKey("KomputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabRepair.Models.Pengguna", "Pelapor")
                        .WithMany()
                        .HasForeignKey("PelaporId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabRepair.Models.Pengguna", "Teknisi")
                        .WithMany()
                        .HasForeignKey("TeknisiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Komputer");

                    b.Navigation("Pelapor");

                    b.Navigation("Teknisi");
                });

            modelBuilder.Entity("LabRepair.Models.Perbaikan", b =>
                {
                    b.HasOne("LabRepair.Models.LaporanKerusakan", "Laporan")
                        .WithMany("Perbaikan")
                        .HasForeignKey("LaporanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabRepair.Models.Pengguna", "Teknisi")
                        .WithMany()
                        .HasForeignKey("TeknisiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Laporan");

                    b.Navigation("Teknisi");
                });

            modelBuilder.Entity("LabRepair.Models.Komputer", b =>
                {
                    b.Navigation("Laporan");
                });

            modelBuilder.Entity("LabRepair.Models.Lab", b =>
                {
                    b.Navigation("Komputer");
                });

            modelBuilder.Entity("LabRepair.Models.LaporanKerusakan", b =>
                {
                    b.Navigation("Perbaikan");
                });
#pragma warning restore 612, 618
        }
    }
}
